# Generated by Django 2.2 on 2020-07-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a drescription for test this can be very long i am just making sure it has neough conentnt to show right there'),
            preserve_default=False,
        ),
    ]
